<?php

namespace App\Presenters;

use App\Core\Config;

/**
 * Prepares data for the Glossary view.
 * Handles the formatting of static data structures (directives, resources, etc.)
 * to keep the Controller clean of presentation logic.
 */
class GlossaryPresenter
{
    private Config $config;

    public function __construct(Config $config)
    {
        $this->config = $config;
    }

    public function getGlossaryData(): array
    {
        return [
            'structures'  => $this->config->get('game_balance.structures'),
            'units'       => $this->config->get('game_balance.training'),
            'armory'      => $this->config->get('armory_items'),
            'edicts'      => $this->config->get('edicts'),
            'directives'  => $this->getDirectives(),
            'allianceOps' => $this->getAllianceOps(),
            'resources'   => $this->getResources()
        ];
    }

    private function getDirectives(): array
    {
        return [
            'industry' => [
                'name' => 'Industrial Revolution',
                'description' => 'A strategic focus on expanding the alliance\'s physical infrastructure.',
                'goal' => '+10% Total Structure Levels',
                'icon' => 'fa-industry',
                'badge' => "Architect's Seal"
            ],
            'military' => [
                'name' => 'Total Mobilization',
                'description' => 'A call to arms to bolster the frontline offensive and defensive capabilities.',
                'goal' => '+10% Total Soldiers & Guards',
                'icon' => 'fa-fighter-jet',
                'badge' => "Warlord's Crest"
            ],
            'intel' => [
                'name' => 'Shadow Protocol',
                'description' => 'A coordination effort to expand the alliance\'s reach through espionage and counter-intelligence.',
                'goal' => '+10% Total Spies & Sentries',
                'icon' => 'fa-user-secret',
                'badge' => "The All-Seeing Eye"
            ],
            'treasury' => [
                'name' => 'Treasury Tithe',
                'description' => 'A fiscal mandate to strengthen the alliance war chest for major operations.',
                'goal' => '+10% Total Bank Credits',
                'icon' => 'fa-coins',
                'badge' => "Golden Handshake"
            ],
            'recruit' => [
                'name' => 'Mass Recruitment',
                'description' => 'An initiative to expand the alliance\'s influence by bringing in new members.',
                'goal' => '+1 Member',
                'icon' => 'fa-users',
                'badge' => "Legion Banner"
            ]
        ];
    }

    private function getAllianceOps(): array
    {
        return [
            'deployment_drill' => [
                'name' => 'Deployment Drill',
                'description' => 'A cooperative wargame where members deploy (sacrifice) soldiers to simulate combat scenarios.',
                'requirement' => 'Soldiers',
                'reward' => 'Global Training Speed Buff',
                'icon' => 'fa-users'
            ],
            'resource_drive' => [
                'name' => 'Resource Drive',
                'description' => 'A logistical operation to stockpile raw credits for alliance infrastructure projects.',
                'requirement' => 'Credits',
                'reward' => 'Bank Interest Buff',
                'icon' => 'fa-coins'
            ],
            'energy_boost' => [
                'name' => 'Energy Mobilization',
                'description' => 'A focus on generating Alliance Energy (AE) to fuel tactical strikes.',
                'requirement' => 'Turns',
                'reward' => 'Immediate AE Injection',
                'icon' => 'fa-bolt'
            ]
        ];
    }

    private function getResources(): array
    {
        return [
            'credits' => [
                'name' => 'Credits',
                'description' => 'The primary currency of the galaxy. Used for constructing buildings, training units, and most transactions.',
                'source' => 'Generated by Economy Upgrade and Workers.',
                'icon' => 'fa-credit-card',
                'color' => 'text-warning'
            ],
            'turns' => [
                'name' => 'Turns',
                'description' => 'A measure of time and logistical capacity. Required to perform major actions like attacking, spying, or manufacturing.',
                'source' => 'Replenished automatically over time (every 15 minutes).',
                'icon' => 'fa-hourglass-half',
                'color' => 'text-info'
            ],
            'protoform' => [
                'name' => 'Protoform',
                'description' => 'Biological sludge used to bio-engineer Generals and Scientists.',
                'source' => 'Acquired through special operations or gameplay mechanics.',
                'icon' => 'fa-flask',
                'color' => 'text-success'
            ],
            'research_data' => [
                'name' => 'Research Data',
                'description' => 'Encrypted data packets used to unlock Embassy Doctrines.',
                'source' => 'Generated by Quantum Research Labs.',
                'icon' => 'fa-database',
                'color' => 'text-primary'
            ]
        ];
    }
}
