<?php

// Start the session, which will be needed for authentication
session_start();

// 1. Autoloader
// This file is generated by Composer and loads all our dependencies and PSR-4 classes
require __DIR__ . '/../vendor/autoload.php';

// 2. Environment Variables
// Load the .env file from the project root
try {
    $dotenv = Dotenv\Dotenv::createImmutable(__DIR__ . '/../');
    $dotenv->load();
} catch (\Dotenv\Exception\InvalidPathException $e) {
    die('Could not find .env file. Please copy .env.example to .env and configure it.');
}

// 3. Error Reporting
// Show all errors in development, but log them and hide them in production
if (($_ENV['APP_ENV'] ?? 'development') === 'development') {
    ini_set('display_errors', 1);
    ini_set('display_startup_errors', 1);
    error_reporting(E_ALL);
} else {
    ini_set('display_errors', 0);
    ini_set('display_startup_errors', 0);
    error_reporting(0);
    
    // Log errors to our logs directory
    ini_set('log_errors', 1);
    ini_set('error_log', __DIR__ . '/../logs/php_errors.log');
}

// 4. Router Definition
// We use FastRoute to define our application's endpoints
$dispatcher = FastRoute\simpleDispatcher(function(FastRoute\RouteCollector $r) {
    
    // Landing Page Route
    // This uses a simple function (a closure) to render a view.
    // This is a temporary setup until we build our BaseController.
    $r->addRoute('GET', '/', function() {
        require __DIR__ . '/../views/landing.php';
    });

    // --- Phase 1: Auth Routes (will be added here) ---
    // $r->addRoute('GET', '/login', ['App\Controllers\AuthController', 'showLogin']);
    // $r->addRoute('POST', '/login', ['App\Controllers\AuthController', 'handleLogin']);
    // $r->addRoute('GET', '/register', ['App\Controllers\AuthController', 'showRegister']);
    // $r->addRoute('POST', '/register', ['App\Controllers\AuthController', 'handleRegister']);
    // $r->addRoute('GET', '/logout', ['App\Controllers\AuthController', 'handleLogout']);

    // --- Phase 2: Dashboard (will be added here) ---
    // $r->addRoute('GET', '/dashboard', ['App\Controllers\DashboardController', 'show']);
});

// 5. Global Error Handler
// A try...catch block to handle all exceptions gracefully
try {
    // 6. Router Dispatch
    // Fetch the HTTP method and URI
    $httpMethod = $_SERVER['REQUEST_METHOD'];
    $uri = $_SERVER['REQUEST_URI'];

    // Strip query string (?foo=bar) and decode the URI
    if (false !== $pos = strpos($uri, '?')) {
        $uri = substr($uri, 0, $pos);
    }
    $uri = rawurldecode($uri);

    // Dispatch the request
    $routeInfo = $dispatcher->dispatch($httpMethod, $uri);

    switch ($routeInfo[0]) {
        case FastRoute\Dispatcher::NOT_FOUND:
            http_response_code(404);
            // In the future, we will render a nice view
            // require __DIR__ . '/../views/errors/404.php';
            echo '404 - Page Not Found';
            break;

        case FastRoute\Dispatcher::METHOD_NOT_ALLOWED:
            http_response_code(405);
            // In the future, we will render a nice view
            // require __DIR__ . '/../views/errors/405.php';
            echo '405 - Method Not Allowed';
            break;

        case FastRoute\Dispatcher::FOUND:
            $handler = $routeInfo[1];
            $vars = $routeInfo[2];

            // Call the handler (our closure, and later, our controller methods)
            call_user_func($handler, $vars);
            break;
    }
} catch (\Throwable $e) {
    // Global exception handler
    http_response_code(500);
    if (($_ENV['APP_ENV'] ?? 'development') === 'development') {
        echo '<h1>Application Error:</h1>';
        echo '<pre>' . $e->getMessage() . '</pre>';
        echo '<pre>File: ' . $e->getFile() . ' on line ' . $e->getLine() . '</pre>';
        echo '<pre>' . $e->getTraceAsString() . '</pre>';
    } else {
        echo 'An unexpected error occurred. Please try again later.';
    }
}