<?php

namespace App\Controllers;

use App\Core\Config;
use App\Core\Session;
use App\Core\CSRFService;
use App\Core\Validator;
use App\Models\Services\ViewContextService;

/**
 * GlossaryController
 * 
 * Displays the game glossary/codex, providing a read-only reference
 * for Structures, Units, Armory items, and Resources.
 */
class GlossaryController extends BaseController
{
    private Config $config;

    public function __construct(
        Config $config,
        Session $session,
        CSRFService $csrfService,
        Validator $validator,
        ViewContextService $viewContextService
    ) {
        parent::__construct($session, $csrfService, $validator, $viewContextService);
        $this->config = $config;
    }

    /**
     * Show the main glossary page.
     */
    public function index(): void
    {
        // 1. Fetch Data
        $structures = $this->config->get('game_balance.structures');
        $training = $this->config->get('game_balance.training');
        $armory = $this->config->get('armory_items');
        $edicts = $this->config->get('edicts');
        $blackMarket = $this->config->get('black_market');
        
        // 1.5 Define Command Directives
        $directives = [
            'industry' => [
                'name' => 'Industrial Revolution',
                'description' => 'A strategic focus on expanding the alliance\'s physical infrastructure.',
                'goal' => '+10% Total Structure Levels',
                'icon' => 'fa-industry',
                'badge' => "Architect's Seal"
            ],
            'military' => [
                'name' => 'Total Mobilization',
                'description' => 'A call to arms to bolster the frontline offensive and defensive capabilities.',
                'goal' => '+10% Total Soldiers & Guards',
                'icon' => 'fa-fighter-jet',
                'badge' => "Warlord's Crest"
            ],
            'intel' => [
                'name' => 'Shadow Protocol',
                'description' => 'A coordination effort to expand the alliance\'s reach through espionage and counter-intelligence.',
                'goal' => '+10% Total Spies & Sentries',
                'icon' => 'fa-user-secret',
                'badge' => "The All-Seeing Eye"
            ],
            'treasury' => [
                'name' => 'Treasury Tithe',
                'description' => 'A fiscal mandate to strengthen the alliance war chest for major operations.',
                'goal' => '+10% Total Bank Credits',
                'icon' => 'fa-coins',
                'badge' => "Golden Handshake"
            ],
            'recruit' => [
                'name' => 'Mass Recruitment',
                'description' => 'An initiative to expand the alliance\'s influence by bringing in new members.',
                'goal' => '+1 Member',
                'icon' => 'fa-users',
                'badge' => "Legion Banner"
            ]
        ];

        // 1.6 Define Alliance Operations (Theater Ops)
        $allianceOps = [
            'deployment_drill' => [
                'name' => 'Deployment Drill',
                'description' => 'A cooperative wargame where members deploy (sacrifice) soldiers to simulate combat scenarios.',
                'requirement' => 'Soldiers',
                'reward' => 'Global Training Speed Buff',
                'icon' => 'fa-users'
            ],
            'resource_drive' => [
                'name' => 'Resource Drive',
                'description' => 'A logistical operation to stockpile raw credits for alliance infrastructure projects.',
                'requirement' => 'Credits',
                'reward' => 'Bank Interest Buff',
                'icon' => 'fa-coins'
            ],
            'energy_boost' => [
                'name' => 'Energy Mobilization',
                'description' => 'A focus on generating Alliance Energy (AE) to fuel tactical strikes.',
                'requirement' => 'Turns',
                'reward' => 'Immediate AE Injection',
                'icon' => 'fa-bolt'
            ]
        ];
        
        // 2. Define Resources (Manual definition as they aren't strictly config-based in the same way)
        $resources = [
            'credits' => [
                'name' => 'Credits',
                'description' => 'The primary currency of the galaxy. Used for constructing buildings, training units, and most transactions.',
                'source' => 'Generated by Economy Upgrade, Accounting Firm, Workers, and Bank Interest.',
                'icon' => 'fa-credit-card',
                'color' => 'text-warning'
            ],
            'turns' => [
                'name' => 'Turns',
                'description' => 'A measure of time and logistical capacity. Required to perform major actions like attacking, spying, or manufacturing.',
                'source' => 'Replenished automatically over time (every 15 minutes).',
                'icon' => 'fa-hourglass-half',
                'color' => 'text-info'
            ],
            'naquadah_crystals' => [
                'name' => 'Naquadah Crystals',
                'description' => 'A rare, high-energy crystal used for advanced technology and purchasing special items from the Black Market.',
                'source' => 'Mined by Naquadah Mining Complex or stolen from other players via Spies.',
                'icon' => 'fa-gem',
                'color' => 'text-neon-blue' // Custom class
            ],
            'dark_matter' => [
                'name' => 'Dark Matter',
                'description' => 'Exotic matter required for super-weapons and ultimate defense structures.',
                'source' => 'Extracted by Dark Matter Siphon.',
                'icon' => 'fa-atom',
                'color' => 'text-purple' // We might need to define this or use a hex
            ],
            'protoform' => [
                'name' => 'Protoform',
                'description' => 'Biological sludge used to bio-engineer Generals and Scientists.',
                'source' => 'Cultivated in Protoform Vats.',
                'icon' => 'fa-flask',
                'color' => 'text-success'
            ],
            'research_data' => [
                'name' => 'Research Data',
                'description' => 'Encrypted data packets used to unlock Embassy Doctrines.',
                'source' => 'Generated by Quantum Research Labs.',
                'icon' => 'fa-database',
                'color' => 'text-primary'
            ]
        ];

        // 3. Render View
        $this->render('glossary/index.php', [
            'title' => 'Game Glossary',
            'structures' => $structures,
            'units' => $training,
            'armory' => $armory,
            'resources' => $resources,
            'edicts' => $edicts,
            'blackMarket' => $blackMarket,
            'directives' => $directives,
            'allianceOps' => $allianceOps
        ]);
    }
}
